const jLeagueTeamList = [
    {header: 'J1'},
    {name: '札幌ドーム', group: 'J1'},
    {name: '県立カシマサッカースタジアム', group: 'J1'},
    {name: '埼玉スタジアム２００２', group: 'J1'},
    {name: '三協フロンテア柏スタジアム', group: 'J1'},
    {name: '味の素スタジアム', group: 'J1'},
    {name: '等々力陸上競技場', group: 'J1'},
    {name: '日産スタジアム', group: 'J1'},
    {name: 'レモンガススタジアム平塚', group: 'J1'},
    {name: 'IAIスタジアム日本平', group: 'J1'},
    {name: 'ヤマハスタジアム(磐田)', group: 'J1'},
    {name: '豊田スタジアム', group: 'J1'},
    {name: 'サンガスタジアム by KYOCERA', group: 'J1'},
    {name: 'パナソニック スタジアム 吹田', group: 'J1'},
    {name: 'ヤンマースタジアム長居', group: 'J1'},
    {name: 'ヨドコウ桜スタジアム', group: 'J1'},
    {name: 'ノエビアスタジアム神戸', group: 'J1'},
    {name: 'エディオンスタジアム広島', group: 'J1'},
    {name: 'ベスト電器スタジアム', group: 'J1'},
    {name: '駅前不動産スタジアム', group: 'J1'},
    { divider: true },
    {header: 'J2'},
    {name: '札幌ドーム', group: 'J2'},
    {name: '県立カシマサッカースタジアム', group: 'J2'},
    {name: '埼玉スタジアム２００２', group: 'J2'},
    {name: '三協フロンテア柏スタジアム', group: 'J2'},
    {name: '味の素スタジアム', group: 'J2'},
    {name: '等々力陸上競技場', group: 'J2'},
    {name: '日産スタジアム', group: 'J2'},
    {name: 'レモンガススタジアム平塚', group: 'J2'},
    {name: 'IAIスタジアム日本平', group: 'J2'},
    {name: 'ヤマハスタジアム(磐田)', group: 'J2'},
    {name: '豊田スタジアム', group: 'J2'},
    {name: 'サンガスタジアム by KYOCERA', group: 'J2'},
    {name: 'パナソニック スタジアム 吹田', group: 'J2'},
    {name: 'ヤンマースタジアム長居', group: 'J2'},
    {name: 'ヨドコウ桜スタジアム', group: 'J2'},
    {name: 'ノエビアスタジアム神戸', group: 'J2'},
    {name: 'エディオンスタジアム広島', group: 'J2'},
    {name: 'ベスト電器スタジアム', group: 'J2'},
    {name: '駅前不動産スタジアム', group: 'J2'},
    { divider: true },
]

export default jLeagueTeamList