const jLeagueTeamList = [
    {header: 'J1'},
    {name: '札幌ドーム', group: 'J1'},
    {name: '県立カシマサッカースタジアム', group: 'J1'},
    {name: '埼玉スタジアム２００２', group: 'J1'},
    {name: '三協フロンテア柏スタジアム', group: 'J1'},
    {name: '味の素スタジアム', group: 'J1'},
    {name: '等々力陸上競技場', group: 'J1'},
    {name: '日産スタジアム', group: 'J1'},
    {name: 'レモンガススタジアム平塚', group: 'J1'},
    {name: 'IAIスタジアム日本平', group: 'J1'},
    {name: 'ヤマハスタジアム(磐田)', group: 'J1'},
    {name: '豊田スタジアム', group: 'J1'},
    {name: 'サンガスタジアム by KYOCERA', group: 'J1'},
    {name: 'パナソニック スタジアム 吹田', group: 'J1'},
    {name: 'ヤンマースタジアム長居', group: 'J1'},
    {name: 'ヨドコウ桜スタジアム', group: 'J1'},
    {name: 'ノエビアスタジアム神戸', group: 'J1'},
    {name: 'エディオンスタジアム広島', group: 'J1'},
    {name: 'ベスト電器スタジアム', group: 'J1'},
    {name: '駅前不動産スタジアム', group: 'J1'},
    { divider: true },
    {header: 'J2'},
    {name: 'いわぎんスタジアム', group: 'J2'},
    {name: 'ユアテックスタジアム仙台', group: 'J2'},
    {name: 'ソユースタジアム', group: 'J2'},
    {name: 'NDソフトスタジアム山形', group: 'J2'},
    {name: 'ケーズデンキスタジアム水戸', group: 'J2'},
    {name: '栃木県グリーンスタジアム', group: 'J2'},
    {name: '正田醤油スタジアム群馬', group: 'J2'},
    {name: 'NACK５スタジアム大宮', group: 'J2'},
    {name: 'フクダ電子アリーナ', group: 'J2'},
    {name: '味の素スタジアム', group: 'J2'},
    {name: '町田GIONスタジアム', group: 'J2'},
    {name: 'ニッパツ三ツ沢球技場', group: 'J2'},
    {name: 'JIT リサイクルインク スタジアム', group: 'J2'},
    {name: 'デンカビッグスワンスタジアム', group: 'J2'},
    {name: '石川県西部緑地公園陸上競技場', group: 'J2'},
    {name: 'シティライトスタジアム', group: 'J2'},
    {name: '維新みらいふスタジアム', group: 'J2'},
    {name: '鳴門・大塚スポーツパーク ポカリスエットスタジアム', group: 'J2'},
    {name: 'トランスコスモススタジアム長崎', group: 'J2'},
    {name: 'えがお健康スタジアム', group: 'J2'},
    {name: '昭和電工ドーム大分', group: 'J2'},
    {name: 'タピック県総ひやごんスタジアム', group: 'J2'},
    { divider: true },
    {header: 'J3'},
    {name: 'プライフーズスタジアム', group: 'J3'},
    {name: 'Jヴィレッジスタジアム', group: 'J3'},
    {name: 'とうほう・みんなのスタジアム', group: 'J3'},
    {name: 'ニッパツ三ツ沢球技場', group: 'J3'},
    {name: '相模原ギオンスタジアム', group: 'J3'},
    {name: 'サンプロ アルウィン', group: 'J3'},
    {name: '長野Ｕスタジアム', group: 'J3'},
    {name: '富山県総合運動公園陸上競技場', group: 'J3'},
    {name: '藤枝総合運動公園サッカー場', group: 'J3'},
    {name: '愛鷹広域公園多目的競技場', group: 'J3'},
    {name: '岐阜メモリアルセンター長良川競技場', group: 'J3'},
    {name: 'Axisバードスタジアム', group: 'J3'},
    {name: 'Pikaraスタジアム', group: 'J3'},
    {name: 'ニンジニアスタジアム', group: 'J3'},
    {name: 'ありがとうサービス. 夢スタジアム', group: 'J3'},
    {name: 'ミクニワールドスタジアム北九州', group: 'J3'},
    {name: 'ユニリーバスタジアム新富', group: 'J3'},
    {name: '白波スタジアム', group: 'J3'}
]

export default jLeagueTeamList